---
kind: Template
apiVersion: v1
metadata:
  name: mpi-example
  annotations:
    iconClass: icon-python
    tags: instant-app,mpi
labels:
  template: mpi-example
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: mpi
    name: mpi-base
  spec:
    lookupPolicy:
      local: false
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: mpi-base
    name: mpi-base
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: mpi-base:latest
    runPolicy: Serial
    source:
      contextDir: /
      git:
        uri: "${MPI_BASE_IMAGE_URI}"
        ref: "${MPI_BASE_IMAGE_REF}"
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile
      type: Docker
    triggers:
    - type: ConfigChange
    successfulBuildsHistoryLimit: 5
    failedBuildsHistoryLimit: 5
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: mpi
    name: mpi
  spec:
    replicas: 3
    selector:
      app: mpi
      deploymentconfig: mpi
    template:
      metadata:
        labels:
          app: mpi
          deploymentconfig: mpi
      spec:
        containers:
        - name: mpi
          image: 'mpi-base'
          imagePullPolicy: Always
          ports:
          - containerPort: 2022
            protocol: TCP
          resources:
            limits:
              cpu: '${MPI_NUMBER_CPUS}'
              memory: '${MPI_MEMORY}'
            requests:
              cpu: '${MPI_NUMBER_CPUS}'
              memory: '${MPI_MEMORY}'
          volumeMounts:
          - mountPath: /etc/ssh/mpi
            name: mpi-ssh
          - mountPath: /.ipython
            name: nfs-mpi-vol 
        volumes:
        - name: nfs-mpi-vol
          persistentVolumeClaim:
            claimName: nfs-pvc-mpi 
        - name: mpi-ssh
          projected:
            defaultMode: 0600
            sources:
            - secret:
                name: mpi-identity
                items:
                - key: ssh-privatekey
                  mode: 0600
                  path: mpi_identity
                - key: ssh-publickey
                  mode: 384
                  path: mpi_identity.pub
            - configMap:
                name: mpi-ssh-config
                items:
                - key: ssh-authorized-keys
                  mode: 0600
                  path: authorized_keys
                - key: ssh-config
                  mode: 0600
                  path: config
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - mpi
        from:
          kind: ImageStreamTag
          name: 'mpi-base:latest'
      type: ImageChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: mpi-master
    name: mpi-master
  spec:
    replicas: 1
    selector:
      app: mpi-master
      deploymentconfig: mpi-master
    template:
      metadata:
        labels:
          app: mpi-master
          deploymentconfig: mpi-master
      spec:
        containers:
        - name: mpi-master
          image: 'mpi-base'
          imagePullPolicy: Always
          ports:
          - containerPort: 2022
            protocol: TCP
          - containerPort: 8888
            protocol: TCP
          resources:
            limits:
              cpu: '${MPI_NUMBER_CPUS}'
              memory: 5Gi
            requests:
              cpu: '${MPI_NUMBER_CPUS}'
              memory: 4096Mi
          volumeMounts:
          - mountPath: /etc/ssh/mpi
            name: mpi-ssh
          - mountPath: /.ipython 
            name: nfs-mpi-vol
        volumes:
        - name: nfs-mpi-vol
          persistentVolumeClaim:
            claimName: nfs-pvc-mpi
        - name: mpi-ssh
          projected:
            defaultMode: 0600
            sources:
            - secret:
                name: mpi-identity
                items:
                - key: ssh-privatekey
                  mode: 0600
                  path: mpi_identity
                - key: ssh-publickey
                  mode: 384
                  path: mpi_identity.pub
            - configMap:
                name: mpi-ssh-config
                items:
                - key: ssh-authorized-keys
                  mode: 0600
                  path: authorized_keys
                - key: ssh-config
                  mode: 0600
                  path: config
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - mpi-master
        from:
          kind: ImageStreamTag
          name: 'mpi-base:latest'
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: mpi-master
    name: mpi-master-svc  
  spec:
    ports:
      - port: 8888
        targetPort: 8888
    selector:
      app: mpi-master
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: mpi-master
    name: mpi-master-route
  spec:
    host: gw-learning.apps.ocp4.info.net
    tls:
      termination: edge 
    to:
      kind: Service
      name: mpi-master-svc
    wildcardPolicy: None
parameters:
- name: MPI_BASE_IMAGE_URI
  description: URI to the git project contianing the saml-service-provider image definintion
- name: MPI_BASE_IMAGE_REF
  description: Git ref contianing the saml-service-provider image definintion
  value: master
- name: MPI_NUMBER_CPUS
  description: Number of CPUs assigned to each mpi pod
  value: "1"
- name: MPI_MEMORY
  description: Memory assigned to each mpi pod
  value: 512Mi
