version: '3'

services:
  head:
    image: mpi-base
    build:
      context: .
      dockerfile: Dockerfile.centos7
    ports:
      - 127.0.0.1:${head_port}:2022
    volumes:
      - ../ssh/sds/:/home/sds/.ssh
      - ../ssh/head/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key
      - ../ssh/head/ssh_host_dsa_key:/etc/ssh/ssh_host_dsa_key
      - ../ssh/head/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key
      - ../ssh/head/ssh_host_ecdsa_key:/etc/ssh/ssh_host_ecdsa_key

  worker1:
    image: mpi-base
    ports:
      - 127.0.0.1:${worker1_port}:2022
    volumes:
      - ../ssh/sds/:/home/sds/.ssh
      - ../ssh/worker1/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key
      - ../ssh/worker1/ssh_host_dsa_key:/etc/ssh/ssh_host_dsa_key
      - ../ssh/worker1/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key
      - ../ssh/worker1/ssh_host_ecdsa_key:/etc/ssh/ssh_host_ecdsa_key

  worker2:
    image: mpi-base
    ports:
      - 127.0.0.1:${worker2_port}:2022
    volumes:
      - ../ssh/sds/:/home/sds/.ssh
      - ../ssh/worker2/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key
      - ../ssh/worker2/ssh_host_dsa_key:/etc/ssh/ssh_host_dsa_key
      - ../ssh/worker2/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key
      - ../ssh/worker2/ssh_host_ecdsa_key:/etc/ssh/ssh_host_ecdsa_key
