apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-mpi-test
spec:
  capacity:
    storage: 2Gi 
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: /nfs/mpi-test 
    server: 192.168.122.2 
    readOnly: false
